### ISSUE TITLE
what is `PWN_COLLEGE_INSTANCE`

### ISSUE THREAD

**Issue by hitfzyangdianshi** [pwncollege/pwncollege#10]
from the docker log, there is an error,` RuntimeError: Configuration Error: PWN_COLLEGE_INSTANCE must be set in the environment`

so what is`PWN_COLLEGE_INSTANCE`. how should I give value to this?

```
Waiting for db: to be ready
db is ready
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app()
  File "/opt/CTFd/CTFd/__init__.py", line 281, in create_app
    init_plugins(app)
  File "/opt/CTFd/CTFd/plugins/__init__.py", line 195, in init_plugins
    module = importlib.import_module(module, package="CTFd.plugins")
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/CTFd/CTFd/plugins/CTFd-pwn-college-plugin/__init__.py", line 19, in <module>
    from .docker_challenge import DockerChallenge, docker_namespace
  File "/opt/CTFd/CTFd/plugins/CTFd-pwn-college-plugin/docker_challenge.py", line 28, in <module>
    from .settings import INSTANCE, HOST_DATA_PATH
  File "/opt/CTFd/CTFd/plugins/CTFd-pwn-college-plugin/settings.py", line 10, in <module>
    "Configuration Error: PWN_COLLEGE_INSTANCE must be set in the environment"
RuntimeError: Configuration Error: PWN_COLLEGE_INSTANCE must be set in the environment
```

**Comment by ConnorNelson** [comment]
A number of commented out values need to be set inside the docker-compose.yml (https://github.com/pwncollege/pwncollege/blob/master/docker-compose.yml#L21).

All of those are expected to have a value except for `BINARY_NINJA_API_KEY` which is optional.

In the case of the 466 instance, those values are:
```
      - PWN_COLLEGE_INSTANCE=cse466
      - HOST_DATA_PATH=/opt/cse466.pwn.college/.data
      - VIRTUAL_HOST=cse466.pwn.college
      - LETSENCRYPT_HOST=cse466.pwn.college
```

`SECRET_KEY` is 32 random hex characters.

**Comment by hitfzyangdianshi** [comment]
got it.
thanks
